version: '3.8'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    command: mlflow server --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    networks:
      - mlflow-net
    volumes:
      - ./mlruns:/mlruns  # Persistent storage for artifacts

networks:
  mlflow-net: